# Generated by Django 3.2.19 on 2023-06-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0003_auto_20230624_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabin',
            old_name='num_guests',
            new_name='max_guests',
        ),
    ]
