# Generated by Django 3.2.19 on 2023-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0006_auto_20230705_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cave_exploration', models.BooleanField(default=False)),
                ('cave_exploration_capacity', models.PositiveIntegerField(default=1)),
                ('cave_exploration_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('rent_kayak', models.BooleanField(default=False)),
                ('kayak_quantity', models.PositiveIntegerField(default=0)),
                ('kayak_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='amenities',
            field=models.ManyToManyField(related_name='cabins', to='cabin_bookings.Amenity'),
        ),
    ]
