# Generated by Django 3.2.19 on 2023-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0008_auto_20230705_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rent_kayak',
            new_name='kayak_rental',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cave_exploration_tickets',
            new_name='num_cave_explorations',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='kayak_quantity',
            new_name='num_kayak_rentals',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cave_exploration_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kayak_price',
        ),
        migrations.AddField(
            model_name='cabin',
            name='cave_exploration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cabin',
            name='kayak_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
