# Generated by Django 3.2.19 on 2023-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0009_auto_20230705_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cave_exploration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kayak_rental',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_cave_explorations',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_kayak_rentals',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='cave_exploration_price',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='kayak_price',
        ),
    ]
