# Generated by Django 3.2.19 on 2023-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0010_auto_20230705_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='include_cave_exploration',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_kayak_rental',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_kayaks',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_tickets',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cabin',
            name='amenities',
            field=models.ManyToManyField(to='cabin_bookings.Amenities'),
        ),
    ]
