# Generated by Django 3.2.19 on 2023-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0012_auto_20230705_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cave_exploration_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='kayak_rentals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cabin',
            name='amenities',
            field=models.ManyToManyField(to='cabin_bookings.Amenity'),
        ),
    ]
