# Generated by Django 3.2.19 on 2023-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0013_auto_20230706_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cave_exploration_tickets',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kayak_rentals',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
