# Generated by Django 3.2.19 on 2023-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_bookings', '0014_auto_20230706_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
